config/routes.rb
Rails.application.routes.draw do
  get "sesiones/new"
  resources :usuarios
  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"


  # Define your application routes here
  resources :productos

  get "registro" => "usuarios#new", as: :registro


  get "login" => "sesiones#new", as: :login
  post "login" => "sesiones#create"
  get "logout" => "sesiones#destroy", as: :logout

  resources :ventas


  #filtrado de productos por su categoria 
  resources :productos do
    collection do
      get 'filtrar/:categoria', to: 'productos#filtrar', as: 'filtrar_categoria'
    end
  end

  resources :productos do
    collection do
      get :buscar
    end
  end

  get '/productos/:id/precio', to: 'productos#precio'

  resources :ventas, only: [:index, :show, :destroy]
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/usuario.rb
class Usuario < ApplicationRecord

  has_many :ventas 
  has_secure_password
  Roles= [:admin, :user, :gerente, :empleado]

  def admin?
    self.rol == 'admin'
  end

  def user?
    self.rol == 'user'
  end 

  def gerente?
    self.rol == 'gerente'
  end

  def empleado?
    self.rol == 'empleado'
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: %i[ show edit update destroy ]
  before_action :usuario_autorizado!

  # GET /usuarios or /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1 or /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
    @roles = if current_user.admin?
              ["Administrador", "Gerente", "Empleado"]
            else
              [ "Gerente", "Empleado"]
    end
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios or /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: "Usuario was successfully created." }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: "Usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  def destroy
    @usuario.destroy!

    respond_to do |format|
      format.html { redirect_to usuarios_path, status: :see_other, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def usuario_autorizado
    unless current_user.admin? || current_user.gerente?
      flash[:danger] = "No tienes permisos para realizar esta acción"
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.expect(usuario: [ :nombre, :email, :password, :password_confirmation, :telefono, :rol_id, :fecha_ingreso ])
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, class:"row g-3") do |form|%>
  <% if usuario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="d-flex flex-column align-items-center">
      <div class="form-group text-center w-50">
        <%= form.label :nombre, style: "display: block",class:"form-label"%>
        <%= form.text_field :nombre, class:"form-control", placeholder:"Ingrese su nombre", aria_label:"default input example"  %>
      </div>

      <div  class="form-group text-center w-50">
        <%= form.label :email, style: "display: block", class:"form-label" %>
        <%= form.text_field :email, class:"form-control", placeholder: "Ingrese su email" %>
      </div>

      <div  class="form-group text-center w-50">
        <%= form.label :contraseña, style: "display: block",class:"form-label" %>
        <%= form.password_field :password,class:"form-control", placeholder: "Ingrese su contraseña" %>
        <div class="col-auto">
          <span id="passwordHelpInline" class="form-text">
            Debe ser de 8-20 caracteres.
          </span>
        </div>
      </div>


      <div  class="form-group text-center w-50">
        <%= form.label :telefono, style: "display: block" %>
        <%= form.text_field :telefono,class:"form-control" %>
      </div>

      <div class="form-group text-center w-50">
        <%= form.label :fecha_ingreso, style: "display: block" %>
        <%= form.date_field :fecha_ingreso,class:"form-control" %>
      </div>
      
      <div class="form-group text-center w-50">
        <%= form.label :rol, style: "display: block" %>
        <%= form.select :rol,@roles,{include_blank: "Seleccione un rol"},class:"form-control" %>
      

      <br>
      <div class="form-actions" style="text-align: center;">
        <%= form.submit "Guardar", class: "btn btn-primary", style: "padding: 10px 20px; background-color: #007bff; color: white; border: none; border-radius: 4px; cursor: pointer;" %>   <%= link_to "Volver", usuarios_path, class: "btn btn-primary", style: "padding: 10px 20px; background-color: #9b9b9b; color: white; border: none; border-radius: 4px; cursor: pointer;" %>

      </div>
    </div>
<% end %>

app/views/usuarios/_usuario.html.erb
<table class="table table-striped bg-light rounded shadow-lg">
  <thead>
    <tr>
      <th><strong>Nombre</strong></th>
      <th><strong>Email</strong></th>
      <th><strong>Teléfono</strong></th>
      <th><strong>Fecha de Ingreso</strong></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= usuario.nombre %></td>
      <td><%= usuario.email %></td>
      <td><%= usuario.telefono %></td>
      <td><%= usuario.fecha_ingreso.strftime('%d/%m/%Y') %></td>
    </tr>
  </tbody>
</table>

app/views/usuarios/edit.html.erb
<% content_for :title, "Editing usuario" %>

<h1>Editing usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Show this usuario", @usuario %> |
  <%= link_to "Back to usuarios", usuarios_path %>
</div>

app/views/usuarios/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Usuarios" %>

<h1>Usuarios</h1>

<div id="usuarios">
  <% @usuarios.each do |usuario| %>
    <%= render usuario %>
  <% end %>
</div>

app/views/usuarios/new.html.erb
<% content_for :title, "Nuevo usuario" %>

<h1>Nuevo usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Lista de usuarios", usuarios_path %>
</div>

app/views/usuarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @usuario %>

<div>
  <%= link_to "Edit this usuario", edit_usuario_path(@usuario) %> |
  <%= link_to "Back to usuarios", usuarios_path %>

  <%= button_to "Destroy this usuario", @usuario, method: :delete %>
</div>