config/routes.rb
Rails.application.routes.draw do
  get "sesiones/new"
  resources :usuarios
  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"


  # Define your application routes here
  resources :productos

  get "registro" => "usuarios#new", as: :registro


  get "login" => "sesiones#new", as: :login
  post "login" => "sesiones#create"
  get "logout" => "sesiones#destroy", as: :logout

  resources :ventas


  #filtrado de productos por su categoria 
  resources :productos do
    collection do
      get 'filtrar/:categoria', to: 'productos#filtrar', as: 'filtrar_categoria'
    end
  end

  resources :productos do
    collection do
      get :buscar
    end
  end

  get '/productos/:id/precio', to: 'productos#precio'

  resources :ventas, only: [:index, :show, :destroy]
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Avivas', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Left Side (Categories) -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Productos', productos_path, method: :get, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Calzado', productos_path(categoria: "Calzado"), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Ropa', productos_path(categoria: "Ropa"), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Accesorios', productos_path(categoria: "Accesorios"), class: "nav-link" %>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Ventas
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'Listar ventas', ventas_path, method: :get, class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to 'Agregar venta', new_venta_path, method: :get, class: "dropdown-item" %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
      
      <!-- Right Side (Profile) -->
      <ul class="navbar-nav ms-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Perfil
          </a>
          <ul class="dropdown-menu dropdown-menu-end">
            <% if logged_in? && (current_user.admin? || current_user.gerente?) %>
              <li>
                <%= link_to 'Agregar usuario', new_usuario_path, method: :get, class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to 'Listar usuarios', usuarios_path, method: :get, class: "dropdown-item" %>
              </li>
            <% end %>
            <li>
              <% if logged_in? %>
                <%= link_to 'Cerrar Sesión', logout_path, method: :delete, class: "dropdown-item" %>
              <% else %>
                <%= link_to 'Iniciar Sesión', login_path, method: :get, class: "dropdown-item" %>
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Avivas" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" crossorigin="anonymous">

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
      <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
    <script type="module" src="application.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
  </body>
</html>